### PR TITLE
Add Gitea support

### PR DESCRIPTION
**Pull request by remram44**
Builds on top of #6 so please review that first.

This adds support for [Gitea](https://gitea.io/en-us/), a popular open-source forge written in Go. The implementation is similar to GitLab, with some instances hardcoded and a heuristic for `gitea.<domain>`

### CODE REVIEW

**Review by rdicosmo — COMMENTED** [review]
Thanks, this is great :-) I'll wait until you confirm that you tested it before merging.
You may also want to have a look at options.html and options.js to see how to add user specified gitea instances.

**Comment by remram44** [comment]
I have tested it on https://codeberg.org/Freeyourgadget/Gadgetbridge ([link to visit](https://archive.softwareheritage.org/browse/origin/directory/?origin_url=https://codeberg.org/Freeyourgadget/Gadgetbridge&timestamp=2022-09-18T21:48:41Z)) and https://git.rampin.org/remi/calendar-booking

<details>
<summary>screenshots</summary>

Gadgetbridge

calendar-booking
</details>

I added an option for custom Gitea instances and tested it on a random one I found via a search:

Gitea instances option

**Comment by rdicosmo** [comment]
Thanks @remram44, this is a great contribution!

**Comment by rdicosmo** [comment]
This is now packaged and online as version 0.6.3 on both FF Add-Ons and CWS.
@remram44

**Pull request merged**
